<?php /* custom header template to remove welcome message */ ?> <?php switch ($block->getShowPart()): case 'welcome': ?> <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }</script><?php break; ?> <?php case 'other': ?> <?php echo $block->getChildHtml(); ?> <?php break; ?> <?php endswitch; ?>