<div class="social">
  <ul class="social-links-container">

    <li><a href="google+" class="social-links"> <span>Google+ </span><img id="google" src='<?php echo $this->getViewFileUrl('images/g.png'); ?>' alt="google+"></a></li>
    <li><a href="instagram" class="social-links"> <span>Instagram </span><img id="instagram" src='<?php echo $this->getViewFileUrl('images/instagram.png'); ?>' alt="instagram"></a></li>
    <li><a href="facebook" class="social-links"> <span>Facebook </span><img id="facebook" src='<?php echo $this->getViewFileUrl('images/facebook.png'); ?>' alt="facebook"></a></li>
    <li><a href="twitter" class="social-links"> <span>Twitter </span><img id="twitter" src='<?php echo $this->getViewFileUrl('images/twitter.png'); ?>' alt="twitter"></a></li>

  </ul>
</div>
